### ISSUE TITLE
Honest question

### ISSUE THREAD

**Issue by yuchi** [alloyui/modal#1]
I see `import`. Why not `class`?

I mean, we’re going ~~ES6~~ ES2015, aren’t we?

**Comment by zenorocha** [comment]
We didn't port all the code yet and this is still a prototype but suggestions are welcome (specially at this point), let's stay in touch ;)

**Comment by eduardolundgren** [comment]
Hey @yuchi, we will definitely use ES6 classes.

* Notice that we are using prototypal inheritance (https://github.com/alloyui/core/blob/master/src/lfr.js#L201), therefore, replacing that to use ES6 classes is a trivial task.
* This is the very first prototype for alloy plugins boilerplate.
* Please, keep watching the repository, any feedback is welcome.

Thanks for the early feedback :+1:
